FROM node:15-alpine

# Create app directory
WORKDIR /app
# Install app dependencies
COPY package*.json ./

RUN npm install 
# Copy app source code
COPY . .

#Expose port and start application
EXPOSE 3001
CMD ["npm", "start"]